# Installation

In [ ]:
pip install chgnet

# Static Calculation (Predict energy, force, stress, magmom)

In [36]:
from chgnet.model.model import CHGNet

# Define Model

chgnet = CHGNet.load()

# Alternatively you can read your own model
# chgnet = CHGNet.from_file(model_path)

CHGNet v0.3.0 initialized with 412,525 parameters
CHGNet will run on cpu


In [37]:
from pymatgen.core import Structure

structure = Structure.from_file('/content/drive/MyDrive/LiCoO2.cif')

print(structure)

Full Formula (Li3 Co3 O6)
Reduced Formula: LiCoO2
abc   :   2.811257   2.811257  13.909456
angles:  90.000000  90.000000 120.000000
pbc   :       True       True       True
Sites (12)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Li    0         0         0
  1  Li    0.666667  0.333333  0.333333
  2  Li    0.333333  0.666667  0.666667
  3  Co    0.333333  0.666667  0.166667
  4  Co    0         0         0.5
  5  Co    0.666667  0.333333  0.833333
  6  O     0         0         0.240007
  7  O     0.666667  0.333333  0.093327
  8  O     0.666667  0.333333  0.57334
  9  O     0.333333  0.666667  0.42666
 10  O     0.333333  0.666667  0.906673
 11  O     0         0         0.759993


/usr/local/lib/python3.12/dist-packages/pymatgen/core/structure.py:3107: UserWarning:

Issues encountered while parsing CIF: 18 fractional coordinates rounded to ideal values to avoid issues with finite precision.



In [ ]:
prediction = chgnet.predict_structure(structure)

for key, unit in [
    ("energy", "eV/atom"),
    ("forces", "eV/A"),
    ("stress", "GPa"),
    ("magmom", "mu_B"),
]:
    print(f"CHGNet-predicted {key} ({unit}):\n{prediction[key[0]]}\n")

CHGNet-predicted energy (eV/atom):
-6.360123634338379

CHGNet-predicted forces (eV/A):
[[-1.1920929e-07 -1.1557713e-06  6.9013331e-06]
 [ 4.4703484e-08 -1.4901161e-07  2.8680079e-06]
 [-8.9406967e-08  8.7742228e-07 -8.9313253e-06]
 [ 2.9802322e-07  6.4005144e-07 -1.5412505e-05]
 [ 1.0728836e-06  2.2917520e-06  3.0947849e-06]
 [-1.1324883e-06 -1.7881393e-07  1.1634213e-05]
 [-1.2218952e-06 -1.1120264e-06  5.6092423e-01]
 [ 1.1771917e-06  1.6689301e-06 -5.6095028e-01]
 [-2.0861626e-07 -1.2218952e-06  5.6092298e-01]
 [-1.3411045e-06 -1.6149133e-06 -5.6092024e-01]
 [ 1.1324883e-06 -2.2165477e-07  5.6094050e-01]
 [ 4.4703484e-07  8.7544322e-08 -5.6091660e-01]]

CHGNet-predicted stress (GPa):
[[-1.0012475e+01  1.7253496e-05  2.1326255e-06]
 [ 1.5662563e-05 -1.0012482e+01 -7.9371250e-07]
 [ 1.5314703e-06 -1.7851001e-07 -9.6903973e+00]]

CHGNet-predicted magmom (mu_B):
[0.00392914 0.00392941 0.00392956 0.32530326 0.32530087 0.32529953
 0.01235986 0.01236007 0.01235968 0.01235977 0.01235998 0.0

In [ ]:
print(prediction)

{'e': array(-6.3601236, dtype=float32), 'm': array([0.00392914, 0.00392941, 0.00392956, 0.32530326, 0.32530087,
       0.32529953, 0.01235986, 0.01236007, 0.01235968, 0.01235977,
       0.01235998, 0.0123598 ], dtype=float32), 's': array([[-1.0012475e+01,  1.7253496e-05,  2.1326255e-06],
       [ 1.5662563e-05, -1.0012482e+01, -7.9371250e-07],
       [ 1.5314703e-06, -1.7851001e-07, -9.6903973e+00]], dtype=float32), 'f': array([[-1.1920929e-07, -1.1557713e-06,  6.9013331e-06],
       [ 4.4703484e-08, -1.4901161e-07,  2.8680079e-06],
       [-8.9406967e-08,  8.7742228e-07, -8.9313253e-06],
       [ 2.9802322e-07,  6.4005144e-07, -1.5412505e-05],
       [ 1.0728836e-06,  2.2917520e-06,  3.0947849e-06],
       [-1.1324883e-06, -1.7881393e-07,  1.1634213e-05],
       [-1.2218952e-06, -1.1120264e-06,  5.6092423e-01],
       [ 1.1771917e-06,  1.6689301e-06, -5.6095028e-01],
       [-2.0861626e-07, -1.2218952e-06,  5.6092298e-01],
       [-1.3411045e-06, -1.6149133e-06, -5.6092024e-01],
     

# Structure Optimization

In [38]:
import numpy as np
from pymatgen.core import Structure

structure = Structure.from_file('/content/drive/MyDrive/LiCoO2.cif')

print(f"original: {structure.get_space_group_info()}")

original: ('R-3m', 166)


In [ ]:
import pandas as pd
from chgnet.model import StructOptimizer

result = StructOptimizer().relax(structure)

print("Relaxed structure:\n")
print(result["final_structure"])

CHGNet v0.3.0 initialized with 412,525 parameters
CHGNet will run on cpu
      Step     Time          Energy          fmax
FIRE:    0 08:22:47      -76.321487        0.560950
FIRE:    1 08:22:48      -76.345566        0.467104
FIRE:    2 08:22:48      -76.380447        0.342201
FIRE:    3 08:22:50      -76.400078        0.220714
FIRE:    4 08:22:51      -76.398758        0.247368
FIRE:    5 08:22:53      -76.399696        0.235225
FIRE:    6 08:22:55      -76.401421        0.211466
FIRE:    7 08:22:56      -76.403625        0.176636
FIRE:    8 08:22:57      -76.406013        0.147827
FIRE:    9 08:22:58      -76.408646        0.137030
FIRE:   10 08:22:59      -76.411415        0.139111
FIRE:   11 08:22:59      -76.413811        0.157040
FIRE:   12 08:23:00      -76.415466        0.176249
FIRE:   13 08:23:01      -76.416817        0.185620
FIRE:   14 08:23:02      -76.418442        0.181364
FIRE:   15 08:23:03      -76.420815        0.167775
FIRE:   16 08:23:04      -76.423973        0.

# Visualize Relaxation

In [39]:
# # 查看方法的文档字符串
# help(StructOptimizer().relax)

trajectory = StructOptimizer().relax(structure, fmax=0.05)["trajectory"]

CHGNet v0.3.0 initialized with 412,525 parameters
CHGNet will run on cpu
      Step     Time          Energy          fmax
FIRE:    0 08:36:41      -76.321487        0.560950
FIRE:    1 08:36:42      -76.345566        0.467104
FIRE:    2 08:36:42      -76.380447        0.342201
FIRE:    3 08:36:43      -76.400078        0.220714
FIRE:    4 08:36:43      -76.398758        0.247368
FIRE:    5 08:36:44      -76.399696        0.235225
FIRE:    6 08:36:44      -76.401421        0.211466
FIRE:    7 08:36:45      -76.403625        0.176636
FIRE:    8 08:36:45      -76.406013        0.147827
FIRE:    9 08:36:46      -76.408646        0.137030
FIRE:   10 08:36:46      -76.411415        0.139111
FIRE:   11 08:36:47      -76.413811        0.157040
FIRE:   12 08:36:47      -76.415466        0.176249
FIRE:   13 08:36:48      -76.416817        0.185620
FIRE:   14 08:36:49      -76.418442        0.181364
FIRE:   15 08:36:49      -76.420815        0.167775
FIRE:   16 08:36:50      -76.423973        0.

In [41]:
e_col = "Energy (eV)"
force_col = "Force (eV/Å)"
df_traj = pd.DataFrame(trajectory.energies, columns=[e_col])
df_traj[force_col] = [
    np.linalg.norm(force, axis=1).mean()  # mean of norm of force on each atom
    for force in trajectory.forces
]
df_traj.index.name = "step"

dft_energy = -76.43
print(f"{dft_energy=:.2f} eV ")

dft_energy=-76.43 eV 


In [ ]:
pip install crystal_toolkit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 30.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 97.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Using cached jupyterlab-3.6.8-py3-none-any.whl.metadata (12 kB)
  Using cached jupyterlab_server-2.27.3-py3-none-any.whl.metadata (5.9 kB)
  Using cached jupyter_ydoc-0.2.5-py3-none-any.whl.metadata (2.2 kB)
  Using cached jupyter_server_ydoc-0.8.0-py3-none-any.whl.metadata (5.3 kB)
  Using cached jupyter_server_fileid-0.9.3-py3-none-any.whl.metadata (4.7 kB)
  Using cached ypy_websocket-0.8.4-py3-none-any.whl.metadata (2.5 kB)
  Using cached y_py-0.6.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
  Using cached json5-0.12.1-py3-none-any.whl.metadata (36 kB)
  Using cached jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
  

In [42]:
import crystal_toolkit.components as ctc
import plotly.graph_objects as go
from crystal_toolkit.settings import SETTINGS
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
from pymatgen.core import Structure

app = Dash(prevent_initial_callbacks=True, assets_folder=SETTINGS.ASSETS_PATH)

step_size = max(1, len(trajectory) // 20)  # ensure slider has max 20 steps
slider = dcc.Slider(
    id="slider", min=0, max=len(trajectory) - 1, step=step_size, updatemode="drag"
)


def plot_energy_and_forces(
    df: pd.DataFrame, step: int, e_col: str, force_col: str, title: str
) -> go.Figure:
    """Plot energy and forces as a function of relaxation step."""
    fig = go.Figure()
    # energy trace = primary y-axis
    fig.add_trace(go.Scatter(x=df.index, y=df[e_col], mode="lines", name="Energy"))
    # get energy line color
    line_color = fig.data[0].line.color

    # forces trace = secondary y-axis
    fig.add_trace(
        go.Scatter(x=df.index, y=df[force_col], mode="lines", name="Forces", yaxis="y2")
    )

    fig.update_layout(
        template="plotly_white",
        title=title,
        xaxis=dict(title="Relaxation Step"),
        yaxis=dict(title=e_col),
        yaxis2=dict(title=force_col, overlaying="y", side="right"),
        legend=dict(yanchor="top", y=1, xanchor="right", x=1),
    )

    # vertical line at the specified step
    fig.add_vline(x=step, line=dict(dash="dash", width=1))

    # horizontal line for DFT final energy
    anno = dict(text="DFT final energy", yanchor="top")
    fig.add_hline(
        y=dft_energy,
        line=dict(dash="dot", width=1, color=line_color),
        annotation=anno,
    )

    return fig


def make_title(spg_symbol: str, spg_num: int) -> str:
    """Return a title for the figure."""
    href = f"https://materialsproject.org/materials/{mp_id}/"
    return f"<a {href=}>{mp_id}</a> - {spg_symbol} ({spg_num})"

title = 'plot'
graph = dcc.Graph(
    id="fig",
    figure=plot_energy_and_forces(df_traj, 0, e_col, force_col, title),
    style={"maxWidth": "50%"},
)

struct_comp = ctc.StructureMoleculeComponent(id="structure", struct_or_mol=structure)

app.layout = html.Div(
    [
        html.H1(
            "Structure Relaxation Trajectory", style=dict(margin="1em", fontSize="2em")
        ),
        html.P("Drag slider to see structure at different relaxation steps."),
        slider,
        html.Div([struct_comp.layout(), graph], style=dict(display="flex", gap="2em")),
    ],
    style=dict(margin="auto", textAlign="center", maxWidth="1200px", padding="2em"),
)

ctc.register_crystal_toolkit(app=app, layout=app.layout)


@app.callback(
    Output(struct_comp.id(), "data"), Output(graph, "figure"), Input(slider, "value")
)
def update_structure(step: int) -> tuple[Structure, go.Figure]:
    """Update the structure displayed in the StructureMoleculeComponent and the
    dashed vertical line in the figure when the slider is moved.
    """
    lattice = trajectory.cells[step]
    coords = trajectory.atom_positions[step]
    structure.lattice = lattice  # update structure in place for efficiency
    assert len(structure) == len(coords)
    for site, coord in zip(structure, coords, strict=True):
        site.coords = coord

    title = make_title(*structure.get_space_group_info())
    fig = plot_energy_and_forces(df_traj, step, e_col, force_col, title)

    return structure, fig


app.run(height=800, use_reloader=False)

<IPython.core.display.Javascript object>